{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "my-nginx-secret",
    "namespace": "nginx-dev",
    "creationTimestamp": null,
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "my-nginx-secret",
        "namespace": "nginx-dev",
        "creationTimestamp": null,
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      }
    },
    "encryptedData": {
      "API_KEY": "AgCLT1TUL6HYU2osIJIfQPzyGmYhDZP6ISvnfZ+8mhsBZe+mSMCJQwS3A4pXejSMMBTvPQpv28ELTxr4ukLqF087oCts60hZH+xcfBvqUy1tGMrGqK0Dd/8DqrSP1KLlubof+t6yu2yna86W7ah5KVUBP6QGj4niyPCoT269e4wqCnGgTpYvxH255bQ7EiSNUgQUJSSKpvTT7qPZN9+Tp5gslB+JOrCnOZiXKlXh1ojvK5qai0MQ9zBXadlgX1kE9t9mL5ksfa50yDKjno5kIxvgU0DaV+ZjgiO52HYrCl1xmd3Kp2k0RYThhUzf/dwqaDTqkx996ny6o3X1R0rWkwbRCksOmBgVKoNbaUHcPi694xM1lszoUvp4DfaFwnurf2yYyBKVd5yzUYffJm/5/QskZeC2AqKB03hFKUIpGMW2qGCh+omOdS2zkSSngN8vVhnCcpaIHJ5+FAf/E9CBARU3Ex7r8wgivhGhFZsw9V1P2NoxTUOYmGW/WsGfv+WD33bNiKk/gYZrX0N5MKJRHKo+zAJdoZ0BfD509b2+S3YCiOsZO/x643gVj2iTf1EXTF7h6hDXV1tEd0LTQBEPTEp+a2rJDXCclKOq1JcvdP0fS/X6nd7NBpDFuz5i4ibx5VBtyLKLWDlvXQVbtT1p3DGN7u11hvgPCt6UhABq8blYgSP4Ar3ui9DYTMYVSf61x4xn2eKqiPV7gxbqL5eqoDcRuWExqDHpDO4="
    }
  }
}
