apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-app.fullname" . }}
  labels:
    {{- include "nginx-app.labels" . | nindent 4 }}
spec:
  # The type is read from your values file (e.g., NodePort or ClusterIP)
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      # NodePort is only added if the type is NodePort
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      name: http
  # The selector links this Service to your Deployment Pods
  selector:
    {{- include "nginx-app.selectorLabels" . | nindent 4 }}
