apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dev-app
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: https://github.com/NoyLevi24/nginx-argo-demo.git
    targetRevision: HEAD
    path: chart/nginx-app
    helm:
      valueFiles:
      - values-dev.yaml 
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-dev 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
